### ISSUE TITLE
can't navigate to R.Layout.activity_main_ceylon

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#521] opened 2016-10-02 11:19 UTC
Given the example `CeylonMainActivity()` in Android Studio, I can't click-navigate to `R.Layout.activity_main_ceylon` or any of the other `static` members of `R.Layout`.

**Comment by bjansen** [comment] 2016-10-02 16:56
I believe this is a duplicate of https://github.com/ceylon/ceylon-ide-intellij/issues/251

**Comment by gavinking** [comment] 2016-10-02 17:30
Well #251 is about wanting to be sent to the XML. This issue is that I don't even get taken to the _Java_. But, sure, I guess fixing #251 is the solution to this.

**Comment by bjansen** [comment] 2016-10-03 20:45
I suppose we could propose two navigation targets like we do for native declarations: one that navigates to the Java decl, the other to the XML file. 
I'll fix the Java part in this issue, and leave the XML part in #251.

**Comment by gavinking** [comment] 2016-10-03 20:51
@bjansen that would be perfect.

**Closed** 2016-10-03 20:53 UTC
Labels: p-high, t-bug

**Comment by gavinking** [comment] 2016-10-03 22:46
Thanks!
