### ISSUE TITLE
Ceylon IntelliJ IDE Fatal Error

### ISSUE THREAD

**Issue by lucono** [ceylon/ceylon-ide-intellij#625] opened 2017-04-03 04:36 UTC
Getting the error below while working with the IntelliJ IDE:

![image](https://cloud.githubusercontent.com/assets/8845985/24595520/4619fef0-1805-11e7-8786-b9d9b5e59b06.png)

```
Method org/intellij/plugins/ceylon/ide/codeInsight/CeylonInlayParameterHintsProvider.getHintInfo(Lcom/intellij/psi/PsiElement;)Lcom/intellij/codeInsight/hints/HintInfo; is abstract
java.lang.AbstractMethodError: Method org/intellij/plugins/ceylon/ide/codeInsight/CeylonInlayParameterHintsProvider.getHintInfo(Lcom/intellij/psi/PsiElement;)Lcom/intellij/codeInsight/hints/HintInfo; is abstract
	at org.intellij.plugins.ceylon.ide.codeInsight.CeylonInlayParameterHintsProvider.getHintInfo(CeylonParameterHintsProvider.ceylon)
	at com.intellij.codeInsight.hints.PopupActionsKt$getHintInfoFromProvider$method$1.value(PopupActions.kt:256)
	at com.intellij.codeInsight.hints.PopupActionsKt$getHintInfoFromProvider$method$1.value(PopupActions.kt)
	at com.intellij.psi.util.PsiTreeUtil.findFirstParent(PsiTreeUtil.java:333)
	at com.intellij.psi.util.PsiTreeUtil.findFirstParent(PsiTreeUtil.java:323)
	at com.intellij.codeInsight.hints.PopupActionsKt.getHintInfoFromProvider(PopupActions.kt:256)
	at com.intellij.codeInsight.hints.PopupActionsKt.access$getHintInfoFromProvider(PopupActions.kt:1)
	at com.intellij.codeInsight.hints.EnableCustomHintsOption.getOptionHintAtOffset(PopupActions.kt:167)
	at com.intellij.codeInsight.hints.EnableCustomHintsOption.isAvailable(PopupActions.kt:159)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.isAvailable(IntentionActionWrapper.java:60)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:130)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$2(ShowIntentionsPass.java:312)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:155)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:311)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getIntentionActionsToShow(ShowIntentionsPass.java:243)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:219)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by bjansen** [comment] 2017-04-03 09:14
It seems to be a duplicate of #623, which has been fixed last week. A nightly build with the fix should be available in a few minutes at this URL: https://ci-ceylon.rhcloud.com/job/ceylon-ide-intellij/

**Closed by bjansen** 2017-04-03 09:14 UTC
