### ISSUE TITLE
Android exception on IntelliJ

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-intellij#497] opened 2016-09-21 10:26 UTC
When I fixed my gradle task, I got this in IntelliJ. I don't get this when compiling the project in Gradle, but it talks about the model loader a lot, so it may be a model loader bug. I hope not.

```ceylon
Cannot convert type name "java.lang.IntArray" to a Declaration: Failed to resolve java.lang.IntArray
com.redhat.ceylon.model.loader.ModelResolutionException: Failed to resolve java.lang.IntArray
	at com.redhat.ceylon.model.loader.AbstractModelLoader$5.call(AbstractModelLoader.java:1782)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$5.call(AbstractModelLoader.java:1690)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:124)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1690)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1686)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.access$1801(IdeModelLoader.ceylon:100)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$10.$call$(IdeModelLoader.ceylon:508)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$10.$call$(IdeModelLoader.ceylon:497)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$1anonymous_0_.call(IdeModelLoader.ceylon:133)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:124)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.callWithLock(IdeModelLoader.ceylon:132)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.convertToDeclaration(IdeModelLoader.ceylon:517)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertDeclaredTypeToDeclaration(AbstractModelLoader.java:644)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertNonPrimitiveTypeToDeclaration(AbstractModelLoader.java:612)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.getNonPrimitiveType(AbstractModelLoader.java:5370)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.obtainType(AbstractModelLoader.java:5270)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.obtainType(AbstractModelLoader.java:5225)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.addValue(AbstractModelLoader.java:3775)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.complete(AbstractModelLoader.java:2892)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.access$1200(AbstractModelLoader.java:100)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$16.run(AbstractModelLoader.java:2369)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:360)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:124)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:357)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.complete(AbstractModelLoader.java:2365)
	at com.redhat.ceylon.model.loader.model.LazyClass$1.run(LazyClass.java:103)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:360)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:124)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:357)
	at com.redhat.ceylon.model.loader.model.LazyClass.load(LazyClass.java:97)
	at com.redhat.ceylon.model.loader.model.LazyClass.getMembers(LazyClass.java:154)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.retrieveInnerDeclarations$priv$(IdeModelLoader.ceylon:251)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.retrieveInnerDeclarations$priv$(IdeModelLoader.ceylon:257)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.access$600(IdeModelLoader.ceylon:100)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$1do_.$do(IdeModelLoader.ceylon:231)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader$4.$call$(IdeModelLoader.ceylon)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:360)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:124)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:357)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.runWithLock(IdeModelLoader.ceylon:127)
	at com.redhat.ceylon.ide.common.model.BaseIdeModelLoader.removeDeclarations(IdeModelLoader.ceylon:244)
	at com.redhat.ceylon.model.loader.model.LazyPackage$5.run(LazyPackage.java:320)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$2.call(AbstractModelLoader.java:360)
	at com.redhat.ceylon.model.loader.AbstractModelLoader$1.call(AbstractModelLoader.java:345)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$1$1.$call$(IdeaModelLoader.ceylon:107)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:207)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.outsideDumbMode(concurrencyManager.ceylon:238)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader$1.$call$(IdeaModelLoader.ceylon:106)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:125)
	at com.intellij.openapi.project.DumbService$2.compute(DumbService.java:119)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:119)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaModelLoader.embeddingSync(IdeaModelLoader.ceylon:103)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedCall(AbstractModelLoader.java:341)
	at com.redhat.ceylon.model.loader.AbstractModelLoader.synchronizedRun(AbstractModelLoader.java:357)
	at com.redhat.ceylon.model.loader.model.LazyPackage.removeUnit(LazyPackage.java:305)
	at com.redhat.ceylon.ide.common.model.JavaUnit.remove(JavaUnit.ceylon:29)
	at com.redhat.ceylon.ide.common.model.JavaUnit.update(JavaUnit.ceylon:38)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.updateUnits$priv$(CeylonProjectBuild.ceylon:785)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.access$1900(CeylonProjectBuild.ceylon:122)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild$27$1$1.$call$(CeylonProjectBuild.ceylon:944)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel$canonical$(CeylonProject.ceylon:446)
	at com.redhat.ceylon.ide.common.model.BaseCeylonProject.withSourceModel(CeylonProject.ceylon:438)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild$27$1.$call$(CeylonProjectBuild.ceylon:914)
	at com.redhat.ceylon.ide.common.model.withCeylonModelCaching_.withCeylonModelCaching(CeylonProjects.ceylon:52)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild$27.$call$(CeylonProjectBuild.ceylon:913)
	at ceylon.interop.java.internal.synchronize_.synchronize(synchronize_.java:33)
	at ceylon.interop.java.synchronize_.synchronize(misc.ceylon:79)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.updateCeylonModel(CeylonProjectBuild.ceylon:912)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild$canonical$(CeylonProjectBuild.ceylon:610)
	at com.redhat.ceylon.ide.common.model.CeylonProjectBuild.performBuild(CeylonProjectBuild.ceylon:580)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$ModelUpdateBackgroundTask$1.$call$(CeylonModelManager.ceylon:317)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withIndexStrategy$priv$(concurrencyManager.ceylon:207)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.concurrencyManager_.withUpToDateIndexes(concurrencyManager.ceylon:228)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.CeylonModelManager$ModelUpdateBackgroundTask.run(CeylonModelManager.ceylon:312)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bjansen** [comment] 2016-09-21 10:27
Probably related, reported by Gavin:

```
1:00:18 AM Plugin Error: Ceylon IDE threw an uncaught ModelResolutionException. Disable Plugin
1:00:18 AM ModelResolutionException: Cannot convert type name "java.lang.CharArray" to a Declaration: Failed to resolve java.lang.CharArray
1:00:19 AM ModelResolutionException: Cannot convert type name "java.lang.ObjectArray" to a Declaration: Failed to resolve java.lang.ObjectArray
1:00:24 AM ModelResolutionException: Cannot convert type name "java.lang.CharArray" to a Declaration: Failed to resolve java.lang.CharArray
1:00:24 AM ModelResolutionException: Cannot convert type name "java.lang.CharArray" to a Declaration: Failed to resolve java.lang.CharArray
1:00:26 AM ModelResolutionException: Cannot convert type name "java.lang.ObjectArray" to a Declaration: Failed to resolve java.lang.ObjectArray
1:00:27 AM ModelResolutionException: Cannot convert type name "java.lang.ObjectArray" to a Declaration: Failed to resolve java.lang.ObjectArray
1:00:34 AM Gradle sync failed: Class com.android.build.gradle.internal.scope.VariantScopeImpl does not implement the requested interface com.android.build.gradle.internal.scope.BaseScope
           Consult IDE log for more details (Help | Show Log)
1:00:43 AM Executing tasks: [clean, :app:generateDebugSources, :app:compileDebugSources]
1:00:46 AM Gradle build finished with 1 error(s) in 12s 577ms
```

**Comment by FroMage** [comment] 2016-09-21 10:48
This only happens with android build tools 2.2.0, not 2.1.0, for some reason.

**Comment by FroMage** [comment] 2016-09-21 12:38
And not always. I can `import java.lang { IntArray }` and use it in my Ceylon code in an Android project in AS, and I get no exception.

**Comment by bjansen** [comment] 2016-09-21 12:40
Can you share a project in which the problem appears all the time?

**Comment by FroMage** [comment] 2016-09-21 12:43
No, I don't have such a project. I'm trying to find how to reproduce it. I can also use declarations from the JDK and from the Android SDK (non-`java.*`) which uses `IntArray` and I get no issue.

**Comment by FroMage** [comment] 2016-09-21 12:47
OK yes. In AS, create a new Android project, with the default everything (empty activity). Wait for the project build to finish. Now add Ceylon to this project and boom.

This appears to be a crash in the IDE itself, because at this point I don't even have ceylon configured in the build file.

**Comment by FroMage** [comment] 2016-09-21 12:53
Yeah, happens every time. Funny thing is that if you create the new project, then change the android build tools down to 2.1.0, and only then configure Ceylon, you will get the exception but your project will be configured properly and you will get the ceylon files and updated gradle build.

**Comment by bjansen** [comment] 2016-09-21 15:24
Do you also see this error prior to the one you reported?

```
2016-09-21 17:19:41,085 [ 556637]   INFO - penapi.project.DumbServiceImpl - Dumb mode not permitted in modal environment; see DumbService.allowStartingDumbModeInside documentation 
java.lang.Throwable
	at com.intellij.openapi.project.DumbServiceImpl.scheduleCacheUpdate(DumbServiceImpl.java:167)
	at com.intellij.openapi.project.DumbServiceImpl.queueTask(DumbServiceImpl.java:92)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.doSynchronizeRoots(ProjectRootManagerComponent.java:300)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.fireRootsChanged(ProjectRootManagerImpl.java:419)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$100(ProjectRootManagerImpl.java:55)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.fireChange(ProjectRootManagerImpl.java:112)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.rootsChanged(ProjectRootManagerImpl.java:125)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.mergeRootsChangesDuring(ProjectRootManagerImpl.java:324)
	at com.intellij.openapi.externalSystem.service.project.AbstractIdeModifiableModelsProvider.commit(AbstractIdeModifiableModelsProvider.java:367)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaCeylonProject.doWithLibraryModel$priv$(IdeaCeylonProject.ceylon:384)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaCeylonProject.addLibraries$priv$$canonical$(IdeaCeylonProject.ceylon:395)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaCeylonProject.addLibraries$priv$(IdeaCeylonProject.ceylon:393)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaCeylonProject.access$200(IdeaCeylonProject.ceylon:130)
	at org.intellij.plugins.ceylon.ide.ceylonCode.model.IdeaCeylonProject$addModuleArchiveHook_$1.$call$(IdeaCeylonProject.ceylon:203)
```

**Comment by FroMage** [comment] 2016-09-22 09:28
Nope.

**Comment by bjansen** [comment] 2016-09-22 17:25
@FroMage I believe I have found an acceptable fix for this one. Could you rebuild master and tell me if it works for you too?

There's an extra problem that I noticed here: right after the project has been created and the Java intention is highlighted correctly, if you configure Ceylon it won't work because the project's `.iml` files haven't been created yet, and we need to know their location to configure Ceylon correctly.

```
null
java.lang.NullPointerException
	at com.intellij.openapi.vfs.VfsUtil.createDirectoryIfMissing(VfsUtil.java:444)
	at org.intellij.plugins.ceylon.ide.ceylonCode.integrations.studio.AndroidStudioSupportImpl.updateGradleModel$priv$(AndroidStudioSupport.ceylon:161)
	at org.intellij.plugins.ceylon.ide.ceylonCode.integrations.studio.AndroidStudioSupportImpl.access$000(AndroidStudioSupport.ceylon:80)
	at org.intellij.plugins.ceylon.ide.ceylonCode.integrations.studio.AndroidStudioSupportImpl$1anonymous_0_$1anonymous_1_.run(AndroidStudioSupport.ceylon:96)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:108)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:117)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:103)
	at com.intellij.openapi.command.WriteCommandAction.access$000(WriteCommandAction.java:34)
	at com.intellij.openapi.command.WriteCommandAction$1.run(WriteCommandAction.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:723)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:82)
	at org.intellij.plugins.ceylon.ide.ceylonCode.integrations.studio.AndroidStudioSupportImpl$1anonymous_0_.run(AndroidStudioSupport.ceylon:100)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:80)
	at org.intellij.plugins.ceylon.ide.ceylonCode.integrations.studio.AndroidStudioSupportImpl.$setupModule(AndroidStudioSupport.ceylon:92)
	at org.intellij.plugins.ceylon.ide.ceylonCode.integrations.studio.ConfigureCeylonAction.actionPerformed(ConfigureCeylonAction.ceylon:13)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:191)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:110)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

The workaround is to leave the IDE and immediately come back, which will persist the `.iml` files.

**Comment by bjansen** [comment] 2016-09-22 17:28
I also randomly get a popup saying something like "Gradle build in progress, are you sure you want to close the project?", I need to figure out where that comes from. Whether I answer "yes" or "no", the project will remain open :s

**Comment by bjansen** [comment] 2016-09-23 10:49
I fixed the NPE but couldn't reproduce the popup.

**Closed** 2016-09-23 10:49 UTC
Labels: c-android, p-high, s-confirmed, t-bug

**Comment by FroMage** [comment] 2016-09-28 09:12
Fixed.

**Comment by FroMage** [comment] 2016-09-28 09:15
I just got the popup, though.
