### ISSUE TITLE
Cannot delete module

### ISSUE THREAD

**Issue by loldrup** [ceylon/ceylon-ide-intellij#606] opened 2017-02-04 13:50 UTC
I tried creating a module (right-click on the source folder and choose New > Ceylon Module) and then immediately deleting it again.

The are no right click options for deleting a module.
I then closed IntelliJ, deleted the module folder manually, and started IntelliJ. The folder had been recreated with all its content!

So how do I get rid of an unwanted module?

**Comment by gavinking** [comment] 2017-02-04 14:26
You can delete package nodes in the Project explorer, but there is no option for deleting module nodes.

**Comment by bjansen** [comment] 2017-02-04 14:31
> The folder had been recreated with all its content!

I don't see how that's possible. Can you reproduce the problem systematically?

**Comment by loldrup** [comment] 2017-02-04 19:11
"I don't see how that's possible. Can you reproduce the problem systematically?"

I just tried it again - same behavior. I'm on Windows 7 with this version:

![intellij version](https://cloud.githubusercontent.com/assets/261940/22620890/efe06f4a-eb15-11e6-9075-8144fa82a299.png)

If you can't reproduce, let me know, then I'll make a video recording of the procedure.

**Comment by bjansen** [comment] 2017-02-04 19:25
I just tried on my machine and I can't reproduce. Are you deleting a subfolder of `source`?

**Comment by loldrup** [comment] 2017-02-04 19:29
Ahh, my bad.
I only deleted the folder in 'modules'. When I delete the folder both in
'modules' and 'source', there's no problem :)

Den 04/02/2017 8.25 PM skrev "Bastien Jansen" <notifications@github.com>:

**Comment by bjansen** [comment] 2017-02-04 19:38
`modules` is the output directory where compiled code goes, so it's automatically recreated when the project is built ;).

Closing, since there no issue.

**Closed by bjansen** 2017-02-04 19:38 UTC
