### ISSUE TITLE
Typing is impossible because of the huge lag

### ISSUE THREAD

**Issue by renatoathaydes** [ceylon/ceylon-ide-intellij#502] opened 2016-09-23 19:24 UTC
IntelliJ has a reputation for being nearly as fast as vim for typing in code.

I use Java a lot in IntelliJ, as well as Kotlin and Groovy. In all languages, I've never observed any lag at all, except when IntelliJ is indexing, which is quite rare.

However, trying to write Ceylon, it's incredibly slow. It looks like for every character typed, the auto-completion is trying to find matches, no matter how fast I type. It's completely impossible to use, and I have the latest Macbook Pro!

And I am talking about a hello world file with a few lines... I don't even want to try it in a large project with large source files (well, I want to try but can't because of this [other bug](https://github.com/ceylon/ceylon-ide-intellij/issues/489) that stops me from importing any of my old projects).

**Comment by bjansen** [comment] 2016-09-23 19:26
What happens if you disable automatic completion? (Settings > Editor > General > Code completion > Autopopup code completion)

**Comment by renatoathaydes** [comment] 2016-09-23 19:40
Yes, as expected that's the problem, without that option enabled it works as expected.

**Comment by bjansen** [comment] 2016-09-23 19:42
OK, thanks, I'll take a look asap. Is your module importing dependencies?

**Comment by renatoathaydes** [comment] 2016-09-23 19:42
No. Hello world, as I said.

**Comment by renatoathaydes** [comment] 2016-09-23 19:44
Wow, In Java and Groovy, I can just type gibberish as fast as I can and it doesn't lag at all, even while quickly showing completion as I type. Probably some very smart caching going on there.

**Comment by bjansen** [comment] 2016-09-23 19:45
Um, that strange, because even when working on ceylon-ide-intellij we don't have such problems. It's the first time someone has this kind of problem afaik.

**Comment by renatoathaydes** [comment] 2016-09-23 19:46
@bjansen In Ceylon files, I am able to type a full word before the editor starts showing the first letter of it! Seriously. You probably haven't noticed because you're coming from Eclipse :D

**Comment by bjansen** [comment] 2016-09-23 19:49
Oh, perhaps try adding more RAM to your IDE (Help > Edit custom VM options). We definitely forgot to mention that in the readme, but the default value makes the IDE lag very fast when it deals with Ceylon projects.

FTR I dislike Eclipse and have been avoiding it for years :)

**Comment by renatoathaydes** [comment] 2016-09-23 19:52
@bjansen please, man! I work with million-line code in Kotlin/Java/Groovy projects, no problem at all there, it's as snappy as it gets. It's the Ceylon plugin that's doing something slow!! And you suggest a hello world program needs more RAM so I can type `"hello"` without lag??

**Comment by bjansen** [comment] 2016-09-23 20:00
Well, you can blame the typechecker for using that much memory. We're not using the same mechanisms as other plugins, because we're trying to reuse existing tools as much as possible.

**Comment by gavinking** [comment] 2016-09-23 20:59
@renatoathaydes you're the only one experiencing this, so calm down please. I'm writing code with Ceylon IDE for IntelliJ _every day_, in a really big project, and I simply don't have any problem with editor responsiveness.

As to RAM usage, while building a helloworld, I have memory usage peaking at about 200 meg, so I doubt the problem is memory usage.

**Comment by gavinking** [comment] 2016-09-25 14:54
@renatoathaydes could you please provide more information about your environment so we can attempt to reproduce this. Thanks.

**Comment by renatoathaydes** [comment] 2016-09-25 16:04
ceylon version 1.3.0 49375fd (Total Internal Reflection)
Computer:
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Intel Core i7
  Processor Speed:	2,5 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
OS
  System Version:	OS X 10.11.6 (15G1004)
  Kernel Version:	Darwin 15.6.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal

IntelliJ IDEA 2016.2.4
Build #IU-162.2032.8, built on September 9, 2016
Licensed to Renato Athaydes
You have perpetual fallback license for this version
JRE: 1.8.0_112-release-b343 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Let me know what else you need to know.

**Comment by gavinking** [comment] 2016-09-25 16:07
Well, that's *very* strange. It's almost identical to my machine:

<blockquote>
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro12,1
  Processor Name:	Intel Core i7
  Processor Speed:	3.1 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	16 GB
</blockquote>

**Comment by renatoathaydes** [comment] 2016-09-25 16:11
I am not able to attach a memory snapshot here as it is too big... would it help anyway? I can create a thread in the user groups for that if necessary.

BTW I have as default a system as you can imagine (all esoteric plugins I install from time to time are disabled/removed!)... while I understand your concern that my system has something strange, I find that difficult to imagine it's the case when I do not face slowness in other languages in IntelliJ.

The slowness I am talking about is probably in the order of 100ms on each keystroke, I'd think. Slow typers may not feel it, but I do feel it a lot.

**Comment by gavinking** [comment] 2016-09-25 16:14
I'm also using the exact same build of IntelliJ, FTR.

**Comment by gavinking** [comment] 2016-09-25 16:15
How much memory have you given IntelliJ? I have:

```
# custom IntelliJ IDEA VM options

-Xms128m
-Xmx3000m
-XX:MaxPermSize=350m
-XX:ReservedCodeCacheSize=240m
-XX:+UseCompressedOops
```

**Comment by renatoathaydes** [comment] 2016-09-25 16:19
```
-Xms128m
-Xmx750m
-XX:ReservedCodeCacheSize=240m
-XX:+UseCompressedOops
```

I will try adding more (but it works fine with monstrous Java projects!)

**Comment by gavinking** [comment] 2016-09-25 16:21
I reduced memory to `-Xmx300m` and I still don't experience any lag at all in a project that is a fair bit more complex than a helloworld.

**Comment by renatoathaydes** [comment] 2016-09-25 16:23
Didn't help at all to raise to `-Xmx3000m`. I see the memory indicator shows around 700MB taken now... but when it GCs, it goes down to 230MB.

**Comment by renatoathaydes** [comment] 2016-09-25 16:27
I would suggest profiling the auto-completion code (which is already proven to be the cause of this lag) and trying to see where it's spending time... I think that when I am typing in characters as fast as I can, the auto-completion code should be doing no work at all... Is it possible to make sure the auto-completer has a timeout for doing any work? So only if I don't type anything for 250ms, for example, does it try to find completions?

**Comment by renatoathaydes** [comment] 2016-09-25 16:30
Also, if you haven't seen this [blog post](https://blog.jetbrains.com/idea/2015/08/experimental-zero-latency-typing-in-intellij-idea-15-eap/), it may help... it seems IntelliJ uses some trick to make typing without lag possible... can the Ceylon plugin be causing the trick to not work (or maybe it just needs to copy the trick?)?

**Comment by gavinking** [comment] 2016-09-25 16:31
> I would suggest profiling the auto-completion code (which is already proven to be the cause of this lag) and trying to see where it's spending time..

Well, no, I don't experience the lag at all, so you would have to do the profiling on *your* machine.

**Comment by gavinking** [comment] 2016-09-25 16:34
> Didn't help at all to raise to `-Xmx3000m`. 

Right, as I said, I still don't experience the problem with only 300 meg.

**Comment by renatoathaydes** [comment] 2016-09-25 16:39
<img width="1177" alt="screen shot 2016-09-25 at 18 38 18" src="https://cloud.githubusercontent.com/assets/1901277/18816723/57aaf11a-834f-11e6-8bae-786a86e97005.png">

**Comment by gavinking** [comment] 2016-09-25 16:40
> The slowness I am talking about is probably in the order of 100ms on each keystroke

So if you type 10 characters quickly, you're waiting almost a second to see the result?

Makes no sense to me. I can't imagine where that could be coming from.

**Comment by gavinking** [comment] 2016-09-25 16:50
@renatoathaydes would you please try two things:

1. Tools > Ceylon > Decrease the processing priority of Ceylon model updates
2. If that doesn't work, then Tools > Ceylon > Disable automatic update of the Ceylon model

Let me know if it makes a difference.

**Comment by gavinking** [comment] 2016-09-25 17:21
@renatoathaydes A third thing you could try would be:

3. In Preferences > Languages & Frameworks > Ceylon > Completion

Disable 'Use colored labels in proposal lists'.

That *shouldn't* make a difference, but it's still worth a try, I suppose.

**Comment by renatoathaydes** [comment] 2016-09-25 18:46
The slowness is subtle but very annoying... hope you can see it in this video (it's non-listed, so should not be searchable):

https://youtu.be/xVqdMFkhsRA

**Comment by renatoathaydes** [comment] 2016-09-25 18:56
@gavinking tried all of the above. No difference.

> So if you type 10 characters quickly, you're waiting almost a second to see the result?

I cannot type 10 characters in less than one second.. what I mean is that each character most certainly takes more than 100ms to show on the screen when I type... does not seem to be cumulative. As the blog post I mentioned before says, it seems this is a slow rendering problem, which does not affect other languages in IntelliJ.

**Comment by gavinking** [comment] 2016-09-25 20:22
@renatoathaydes That looks to me like *way* less than a 1/10th of a second lag. Sure, there's a *slight*, almost imperceptible, difference in the speed at which typed characters are displayed. But in the issue description you state that the editor is "incredibly slow", and "completely impossible to use", and I'm not seeing anything remotely like that in your video. Perhaps you have some other scenario in which the editor becomes unusable, but this video doesn't show anything like that.

So, yes, I do see a teensy tiny subtle delay in between keypress and displaying a character when typing many characters quickly when autopop completion is enabled. Obviously our `CompletionProvider` is adding a bit more overhead than it should, and we should try to optimize that. Of course, this is the very first release of our plugin, and there's surely lots of other room for optimization.

But this is hardly something catastropic that makes the editor unusable, AFAICT, and so your description of the issue just sent us down the wrong track completely.

**Comment by renatoathaydes** [comment] 2016-09-25 20:46
That's why I made the video, you seemed to assume it was like a second delay... no, it's a small delay (at least 100 ms or I probably would not notice) that throws me off completely when writing code, so for me it is totally unusable.

You are probably used to it and can't notice anymore.

Subjective? Yes for sure... close the issue if you don't mind this, but I will not use it.

**Comment by gavinking** [comment] 2016-09-25 20:57
> Subjective? Yes for sure... close the issue if you don't mind this, but I will not use it.

FFS man, we're just trying to understand what the actual problem is so we can nail down the source of it and fix it! And you're making that way more difficult than it needs to be by being amazingly combative and by wildly exaggerating the nature of the problem.

**Comment by gavinking** [comment] 2016-09-25 22:00
Alright, so, I have done two things:

1. I commented out a `print()` statements I added when I was profiling the completion subsystem.
2 On the 502 branch, I have pushed @02550a0d3c8f36e6fe2099f0747d855effc32f1a.

It seems to me that these two changes have solved the problem. It's really hard to be certain of how much impact each one had because this problem is so subtle that I don't have a hope of measuring the impact. But subjectively it seems to me that the behavior noticed by @renatoathaydes is fixed.

_Unfortunately,_ @02550a0d3c8f36e6fe2099f0747d855effc32f1a isn't quite right, and breaks member completion, due to what appears to be a mismatch between the token stream and the AST. Nevertheless, it doesn't seem as wildly broken as I had feared.

**Comment by gavinking** [comment] 2016-09-25 23:25
> _Unfortunately,_ @02550a0d3c8f36e6fe2099f0747d855effc32f1a isn't quite right, and breaks member completion, due to what appears to be a mismatch between the token stream and the AST. Nevertheless, it doesn't seem as wildly broken as I had feared.

Looks like I have got around this via some hackery.

It seems to me like the problem is fixed, but it's perfectly possible that I've introduced bugs.

**Comment by gavinking** [comment] 2016-09-25 23:30
The best thing about this change is it makes completion popup *waaay* faster...

**Comment by gavinking** [comment] 2016-09-26 00:34
My solution seems to be working pretty well, and makes completion come up a lot quicker, so I've merged it to master (as a single commit to make it easy to roll back).

**Comment by renatoathaydes** [comment] 2016-09-26 06:24
> FFS man, we're just trying to understand what the actual problem is so we can nail down the source of it and fix it! And you're making that way more difficult than it needs to be by being amazingly combative and by wildly exaggerating the nature of the problem.

I am amazed you have this impression. I've just spent a Sunday night helping you solve a problem (without having anything to gain and much to lose, for example, my peace of mind) by providing you with all information you requested, doing your job for you by opening up a visualVM and showing what part of the code is slow (why couldn't you do that??), and even going as far as making a video to clarify what the problem is because you think this is a non-issue (again, you think I am exaggerating, I think I am not even close... yes, this is a subjective issue and I have the right to say the IDE is unusable for me, you cannot tell me what to judge as good or bad). If this is what you call "amazingly combative", good luck with having any users at all.

**Comment by gavinking** [comment] 2016-09-26 08:17
> doing your job for you by opening up a visualVM and showing what part of the code is slow (why couldn't you do that??)

FTR, the slowness was not related to anything of the methods that showed up in that Visual VM screenshot.

And if you would have accurately described the problem in the first place as a tiny subtle lag, instead of talking about an editor that was "incredibly slow", and "completely impossible to use", then we would not have thought that this was something that we were unable to reproduce, and I would not have wasted time asking for all sorts of information about your environment. We would have been able to investigate and fix the issue _much_ more quickly, without you needing to "do [my] job for [me]", and neither of us would have wasted so much time on this.

The problem here was that the original issue description did not contain an accurate description of the problem, and even after much back and forth, we didn't get an accurate description until you posted the video 29 comments into this thread, after yelling at Bastien, and after bashing us on reddit. And the whole time we were just trying to figure out what on earth was going on so that we could get the problem fixed!

**Comment by bjansen** [comment] 2016-09-27 11:56
It seems to me that the situation is now much more acceptable, so I'll close this for now.

**Closed by bjansen** 2016-09-27 11:56 UTC
Labels: t-performance
