### ISSUE TITLE
autocompletion broken in certain locations

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#377] opened 2016-07-22 16:24 UTC
Given this exact code:

```ceylon
void test() {
    Arr<here>
    if (true) {
        return;
    }
    else {
    }
}
```

Autocompletion returns no proposals. This bug does not affect the Eclipse plugin, which is weird.

**Comment by gavinking** [comment] 2016-07-22 16:29
Also it seems to have swallowed the parser errors in this case. Something *extremely* screwy here.

**Comment by gavinking** [comment] 2016-07-22 16:33
Do parse errors somehow crash the whole typechecking process? @davidfestal ?

**Comment by bjansen** [comment] 2016-07-22 16:40
I see an endless loop of these:

```
[4702900]  ERROR - .psi.impl.DocumentCommitThread -  
java.lang.AssertionError: Text mismatch in FILE
	at com.intellij.psi.impl.source.tree.LazyParseableElement.assertTextLengthIntact(LazyParseableElement.java:227)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:213)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:240)
	at com.intellij.psi.impl.source.text.DiffLog$ReplaceElementWithEvents.<init>(DiffLog.java:263)
	at com.intellij.psi.impl.source.text.DiffLog$ReplaceElementWithEvents.<init>(DiffLog.java:254)
	at com.intellij.psi.impl.source.text.DiffLog.appendReplaceElementWithEvents(DiffLog.java:74)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.replaceElementWithEvents(BlockSupportImpl.java:261)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:278)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.makeFullParse(BlockSupportImpl.java:216)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.reparseRange(BlockSupportImpl.java:92)
	at com.intellij.psi.impl.DocumentCommitThread.doCommit(DocumentCommitThread.java:803)
	at com.intellij.psi.impl.DocumentCommitThread$6.run(DocumentCommitThread.java:581)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1033)
	at com.intellij.psi.impl.DocumentCommitThread.commitUnderProgress(DocumentCommitThread.java:599)
	at com.intellij.psi.impl.DocumentCommitThread.access$400(DocumentCommitThread.java:81)
	at com.intellij.psi.impl.DocumentCommitThread$2.run(DocumentCommitThread.java:415)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.psi.impl.DocumentCommitThread.pollQueue(DocumentCommitThread.java:412)
	at com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:362)
	at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bjansen** [comment] 2016-07-22 16:43
The assert is: 
```
    assert length == expected : "Text mismatch in " + getElementType();
```

with `expected == 78` (that's correct), and `length == 70`, which is wrong. It looks like because of the parse error, we don't add an "invalid code" token at the end of the AST, which leads to all those errors.

**Comment by bjansen** [comment] 2016-07-22 17:19
Should be fixed. @davidfestal don't forget to include this fix when you rewrite IdeaCeylonParser in Ceylon: https://github.com/ceylon/ceylon-ide-intellij/commit/ba72ad908f0da85ba30235dd3c1c2e927b631ed7

**Closed** 2016-07-22 17:19 UTC
Labels: t-bug

**Comment by bjansen** [comment] 2016-07-22 17:30
BTW this is a regression introduced in 72d0bb8bb95962a1bb37d29b1bbdea6c24df54ec, when I subclassed `CeylonLexer`, overriding `nextToken` had the nice side effect to automatically create a "bad code" token at the end of the list during the last call of `nextToken`.

**Comment by gavinking** [comment] 2016-07-22 18:00
Excellent, thanks! This one was stressing me.
