### ISSUE TITLE
adding or removing a shortcut refinement does not immediately trigger a model update

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#475] opened 2016-09-11 20:00 UTC
I *think* the expected behavior is that after adding or removing a shortcut refinement, I should just wait 4 secs to see the impact. At least that's what seems to happen with regular refinements.

**Comment by bjansen** [comment] 2016-09-12 06:30
Which one do you want? An immediate model update, or wait 4s?

**Comment by gavinking** [comment] 2016-09-12 06:39
Well wait 4s. Instead of having to switch Windows which is what I have to do now. It should behave the same as for regular refinement.

**Comment by bjansen** [comment] 2016-09-12 09:23
Is this happening when you manually type a shortcut refinement, or when you call the "Convert to shortcut refinement" intention?

**Comment by gavinking** [comment] 2016-09-12 09:33
When I type it in manually.

**Comment by bjansen** [comment] 2016-09-12 10:00
Given this code:

```ceylon
interface Hello {
    shared formal Integer foo;
}

class World() satisfies Hello {
}
```

when I manually type `foo => 1;`, after 4s a model update is run and removes the error in the problems view. Is this scenario similar to yours?

**Comment by gavinking** [comment] 2016-09-12 10:01
yes.

**Comment by gavinking** [comment] 2016-09-12 10:02
Try refining `highlighter` in `AbstractCeylonColorSettingsPage`.

**Comment by bjansen** [comment] 2016-09-12 10:30
OK, I think it's because `AbstractCeylonColorSettingsPage` is `abstract`, so perhaps the diff system makes less checks than for non-abstract classes.

**Comment by davidfestal** [comment] 2016-09-12 10:48
@bjansen  I don't see why

**Comment by davidfestal** [comment] 2016-09-12 10:51
it's probably a bug.

I'll have a look in the delta builder.

**Comment by bjansen** [comment] 2016-09-12 12:10
Steps to reproduce:

```ceylon
interface Hello {
    shared formal Integer foo;
}

abstract class World() satisfies Hello {
//    foo => 2;
}

class Foo() extends World() {
    foo => 1;
}
```

Uncomment the line and wait for 4s: the model is not updated. 
Comment the line, remove the `abstract` annotation, manually update the model, then uncomment the line: the model is updated after 4s.

**Comment by bjansen** [comment] 2016-09-15 12:09
Is this one fixed? It looks like your commit message didn't close it automatically.

**Comment by davidfestal** [comment] 2016-09-15 12:12
I fixed the cause in the delta builder, but didn't get the time to test
again in IntelliJ (I'm on Eclipse now).
I wanted to do it before closing the issue, but maybe you can easily
confirm that this now works ?

2016-09-15 14:09 GMT+02:00 Bastien Jansen <notifications@github.com>:

**Comment by bjansen** [comment] 2016-09-15 12:12
Sure.

**Comment by bjansen** [comment] 2016-09-15 12:16
The case I mentioned here now works fine: https://github.com/ceylon/ceylon-ide-intellij/issues/475#issuecomment-246328199

Closing.

**Closed by bjansen** 2016-09-15 12:16 UTC
Labels: t-bug
