### ISSUE TITLE
`CeylonModelManager`: Review model update triggering for descriptors

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-intellij#216] opened 2016-06-01 09:16 UTC
Currently, with the periodic model update, as soon as a change is made to a module descriptor, a full typechecking (with module validation and classpath resolution) is triggered or can be.  We should manage to avoid starting model updates in unnecessary case (when the module descriptor is incomplete or has syntax errors for example).
Maybe periodic updates is not the good solution. And we should find another way to trigger the model update.

**Comment by bjansen** [comment] 2016-06-01 09:20
FTR I disabled the periodic update that was defaulted to `true`, partly because of that (I also had that kind of problem each time I typed a character in a Java file).

**Comment by davidfestal** [comment] 2016-06-01 09:24
@bjansen : can you explain a bit more about the Java problem ?

**Comment by bjansen** [comment] 2016-06-01 09:41
Hum no I can't reproduce that anymore, but I had the impression that as soon as I was modifying a Java file, it triggered a model update (more often than every 5s).

**Comment by davidfestal** [comment] 2016-06-09 19:24
Alrady finished for a while? I forgot to close the issue.

**Comment by bjansen** [comment] 2016-06-11 16:31
You still haven't closed it ;)

**Comment by davidfestal** [comment] 2016-06-11 20:41
Haha, right!

**Closed** 2016-06-11 20:42 UTC
Labels: t-enhancement, t-task
