### ISSUE TITLE
Find > Highlight Usages in File broken for Tree and Visitor

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#421] opened 2016-08-24 11:37 UTC
Find functionality doesn't work quite right for certain types, namely `Tree` and `Visitor` in `com.redhat.ceylon.compiler.typechecker.tree`. It's easiest to see this with Highlight Usages in File. But even just regular occurrence highlighting demonstrates the problem:

<img width="749" alt="screen shot 2016-08-24 at 1 36 27 pm" src="https://cloud.githubusercontent.com/assets/579974/17929301/dbcaa2a6-69ff-11e6-856e-a1e9231872df.png">

**Comment by bjansen** [comment] 2016-08-24 12:15
That's a very odd bug.

**Comment by gavinking** [comment] 2016-08-24 12:39
Yep.

**Comment by bjansen** [comment] 2016-09-05 15:53
I can't reproduce anymore on that particular case.

**Comment by bjansen** [comment] 2016-09-05 15:56
@gavinking is it fixed for you too?

**Comment by gavinking** [comment] 2016-09-05 18:17
No, it's still happening. In both `FindReferencesVisitor` and `MemberNameCompletion`.

Interestingly, when I first opened the file it didn't happen ... but then after a model update it went back to broken.

**Comment by bjansen** [comment] 2016-09-06 10:04
I believe this is a bug in IntelliJ, that has been fixed in 2016.3 EAP, in which I can't reproduce the problem.

Most likely this fix: https://github.com/JetBrains/intellij-community/commit/a3f044d3add6d1a1e852a770cc025f1223651a02

**Comment by gavinking** [comment] 2016-09-06 10:05
OK, I'm using 2016.2.3 so that could explain it.

**Closed** 2016-09-06 10:06 UTC
Labels: t-bug
