### ISSUE TITLE
in CeylonVariableRenameHandler.isAvailable() it should check whether or not a ceylon file is being edited

### ISSUE THREAD

**Issue by gertjana** [ceylon/ceylon-ide-intellij#102] opened 2016-03-08 13:49 UTC
When refactoring/renaming a method in another language i'm still offered the choice to use the ceylon refactoring. just by having the ceylon plugin installed

![screen shot 2016-03-08 at 12 58 20](https://cloud.githubusercontent.com/assets/496555/13603344/d91daa46-e53c-11e5-91ae-e683eb873194.png)

**Comment by bjansen** [comment] 2016-03-08 13:52
Duplicate of https://github.com/ceylon/ceylon-ide-intellij/issues/98

**Comment by bjansen** [comment] 2016-03-08 13:53
Thanks anyway :)

**Closed by bjansen** 2016-03-08 13:52 UTC

**Comment by quintesse** [comment] 2016-03-08 14:02
Perhaps time for a new dev build? (#98 was closed in december)

**Comment by gertjana** [comment] 2016-03-08 14:02
no problem, only looked in the open issues for duplicates.
btw I usually close issues after release only ;)

**Comment by bjansen** [comment] 2016-03-14 16:18
I uploaded a new build, see the instructions [in the README](https://github.com/ceylon/ceylon-ide-intellij/blob/master/README.md#install-from-the-development-plugin-repository) on how to install.

**Comment by gertjana** [comment] 2016-03-14 16:31
Macosx 10.11.3, Intellij 15.0.3
 - updated repository to include the `/legacy` part, 
 - updated both runtime and IDE plugins (1.2.2-v201603141558) and got this:

Plugin 'org.intellij.plugins.ceylon.ide' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NoClassDefFoundError: com/redhat/ceylon/compiler/java/runtime/metamodel/Metamodel
    at org.intellij.plugins.ceylon.runtime.CeylonRuntime.registerModule(CeylonRuntime.java:126)
    at org.intellij.plugins.ceylon.runtime.CeylonRuntime.registerIntellijApiModules(CeylonRuntime.java:105)
    at org.intellij.plugins.ceylon.ide.IdePluginCeylonStartup.initComponent(IdePluginCeylonStartup.java:29)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:518)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
    at com.intellij.openapi.application.impl.ApplicationImpl.access$801(ApplicationImpl.java:91)
    at com.intellij.openapi.application.impl.ApplicationImpl$12.run(ApplicationImpl.java:497)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:512)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:455)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:447)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:60)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:361)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel PluginClassLoader[org.intellij.plugins.ceylon.runtime, 1.2.2-v201603141558]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 37 more

**Comment by bjansen** [comment] 2016-03-14 16:44
I'll have a look at this

**Comment by bjansen** [comment] 2016-03-14 18:34
There was an API incompatibility in IntelliJ 15, I found a fix and uploaded yet another build. This one should work ;)

**Comment by gertjana** [comment] 2016-03-14 19:32
I can confirm this one works :)
thx!
