### ISSUE TITLE
lots of 'Unsupported token type' errors

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-intellij#380] opened 2016-07-24 11:14 UTC
```
Unsupported token type [@-1,61767:61821='<EOF>',<-2>,0:-1]
java.lang.UnsupportedOperationException: Unsupported token type [@-1,61767:61821='<EOF>',<-2>,0:-1]
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$CompilationUnitTranslator.buildLeaf(IdeaCeylonParser.java:318)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$CompilationUnitTranslator.visit(IdeaCeylonParser.java:200)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser$CompilationUnitTranslator.translateToAstNode(IdeaCeylonParser.java:183)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.IdeaCeylonParser.doParseContents(IdeaCeylonParser.java:108)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:237)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:39)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzerManager$10$2$1.$call$(CeylonLocalAnalyzerManager.ceylon:248)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:850)
	at org.intellij.plugins.ceylon.ide.ceylonCode.psi.CeylonLocalAnalyzerManager$10$2.$call$(CeylonLocalAnalyzerManager.ceylon:245)
	at ceylon.interop.java.JavaRunnable.run(JavaRunnable.ceylon:7)
	at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:58)
	at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:72)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:327)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:863)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by bjansen** [comment] 2016-07-26 14:00
It happens again in IdeCompletionManager.ceylon :(

**Comment by davidfestal** [comment] 2016-08-09 13:48
This shouldn't happen anymore since the root cause (#389) has been fixed.
@gavinking, @bjansen: do you confirm ?

**Comment by davidfestal** [comment] 2016-08-10 11:07
let me close it. And please reopen it if you still encounter a problem @bjansen and @gavinking

**Closed by davidfestal** 2016-08-10 11:07 UTC
Labels: p-high, s-waiting for answer, t-bug
