### ISSUE TITLE
InvalidClass in AS

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-ide-intellij#424] opened 2016-08-24 14:37 UTC
```
Element: class com.intellij.psi.impl.compiled.ClsFileImpl because: jar:///home/stephane/.AndroidStudio2.1/config/plugins/CeylonIDEA/classes/embeddedDist/repo/ceylon/language/1.2.3/ceylon.language-1.2.3.car!/ceylon/language/digitOrSign_.class is invalid
invalidated at: no info
com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.compiled.ClsFileImpl because: jar:///home/stephane/.AndroidStudio2.1/config/plugins/CeylonIDEA/classes/embeddedDist/repo/ceylon/language/1.2.3/ceylon.language-1.2.3.car!/ceylon/language/digitOrSign_.class is invalid
invalidated at: no info
	at com.intellij.psi.impl.compiled.ClsFileImpl.getContainingFile(ClsFileImpl.java:148)
	at com.jetbrains.cidr.lang.symbols.symtable.FileSymbolTablesCache$OCCodeBlockModificationListener.treeChanged(FileSymbolTablesCache.java:1036)
	at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:395)
	at com.intellij.psi.impl.PsiManagerImpl.childRemoved(PsiManagerImpl.java:318)
	at com.intellij.psi.impl.file.impl.PsiVFSListener$5.run(PsiVFSListener.java:218)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.fileDeleted(PsiVFSListener.java:212)
	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.fireAfter(BulkVirtualFileListenerAdapter.java:85)
	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.after(BulkVirtualFileListenerAdapter.java:56)
	at com.intellij.psi.impl.file.impl.PsiVFSListener$1.after(PsiVFSListener.java:87)
	at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:368)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:355)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:332)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:223)
	at com.sun.proxy.$Proxy29.fileWithNoDocumentChanged(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.multiCast(FileDocumentManagerImpl.java:139)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.access$000(FileDocumentManagerImpl.java:86)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1.invoke(FileDocumentManagerImpl.java:117)
	at com.sun.proxy.$Proxy29.fileWithNoDocumentChanged(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.contentsChanged(FileDocumentManagerImpl.java:623)
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
	at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
	at com.sun.proxy.$Proxy23.contentsChanged(Unknown Source)
	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.fireAfter(BulkVirtualFileListenerAdapter.java:65)
	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.after(BulkVirtualFileListenerAdapter.java:56)
	at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:368)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:355)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:334)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:42)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:223)
	at com.sun.proxy.$Proxy25.after(Unknown Source)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvents(PersistentFSImpl.java:796)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEventsInWriteAction(RefreshSessionImpl.java:223)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl$1$1.run(RefreshSessionImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl$1.run(RefreshSessionImpl.java:193)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEvents(RefreshSessionImpl.java:206)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl$1$1.run(RefreshQueueImpl.java:91)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by bjansen** [comment] 2016-08-29 08:43
Actually there's nothing related to Ceylon IDE in this stack trace, it looks like this is caused by one of JetBrains' plugins, so I'm closing this one as invalid.

**Comment by FroMage** [comment] 2016-08-29 09:41
`com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.compiled.ClsFileImpl because: jar:///home/stephane/.AndroidStudio2.1/config/plugins/CeylonIDEA/classes/embeddedDist/repo/ceylon/language/1.2.3/ceylon.language-1.2.3.car!/ceylon/language/digitOrSign_.class is invalid`

**Comment by FroMage** [comment] 2016-08-29 09:41
You must have missed this ;)

**Comment by bjansen** [comment] 2016-08-29 09:44
Right, some plugin tried to load a file which happens to be in language.car, that doesn't mean it's our fault if this plugin is broken :)

**Comment by FroMage** [comment] 2016-08-29 09:56
Well, can't we do anything to prevent this crash? The class is not invalid…

**Comment by bjansen** [comment] 2016-08-29 10:25
The message is a bit misleading, the class is valid, but the containing file has been invalidated, most likely because its content changed and was reindexed by IntelliJ.

@davidfestal do you think this is related to our own `VirtualFileListener`? (it looks like the stack involves file change events)

**Comment by davidfestal** [comment] 2016-08-29 10:45
I don't see our listener in the stack trace. So nothing shows our listener in involved. We should debug this with an exception breakpoint, and see where this invalid PSI element comes from.

**Comment by bjansen** [comment] 2016-08-29 16:14
`FileSymbolTablesCache$OCCodeBlockModificationListener` is trying to get the containing file of `digitOrSign_.class`, which has apparently been removed from `ceylon.language`, so of course it fails.

AFAIU, this error could happen with any class removed from any JAR, the fact that it happens to be in one of our archives is simply a coincidence. I think there's nothing we can do here.

**Closed by bjansen** 2016-08-29 16:14 UTC
Labels: s-wontfix, t-bug

**Comment by FroMage** [comment] 2016-08-30 08:48
OK thanks.
