### ISSUE TITLE
Compilation errors not shown.

### ISSUE THREAD

**Issue by sollecitom** [ceylon/ceylon-ide-intellij#629] opened 2017-04-12 14:51 UTC
IntelliJ IDEA 2017.1.1
Build #IC-171.4073.35, built on April 6, 2017
JRE: 1.8.0_121-b13 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Linux 4.10.0-14-generic (Linux Mint 18.1)

When I modify a file, compilation errors are not shown until I rebuild the project. Even there, they are outlined in the issues section but not underlined in the editor itself.

Ceylon compiler tab under settings does not load.

I have the following error notification every time I start Intellij Idea:

```
Method
org/intellij/plugins/ceylon/ide/codeInsight/CeylonInlayParameterHintsProvider.getHintInfo(Lcom/intellij/psi/PsiElement;)Lcom/intellij/codeInsight/hints/HintInfo; is abstract
java.lang.AbstractMethodError: Method org/intellij/plugins/ceylon/ide/codeInsight/CeylonInlayParameterHintsProvider.getHintInfo(Lcom/intellij/psi/PsiElement;)Lcom/intellij/codeInsight/hints/HintInfo; is abstract
	at org.intellij.plugins.ceylon.ide.codeInsight.CeylonInlayParameterHintsProvider.getHintInfo(CeylonParameterHintsProvider.ceylon)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.process(ParameterHintsPassFactory.java:122)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.lambda$doCollectInformation$2(ParameterHintsPassFactory.java:94)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.doCollectInformation(ParameterHintsPassFactory.java:94)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)


java.lang.AbstractMethodError: Method org/intellij/plugins/ceylon/ide/codeInsight/CeylonInlayParameterHintsProvider.getHintInfo(Lcom/intellij/psi/PsiElement;)Lcom/intellij/codeInsight/hints/HintInfo; is abstract
	at org.intellij.plugins.ceylon.ide.codeInsight.CeylonInlayParameterHintsProvider.getHintInfo(CeylonParameterHintsProvider.ceylon)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.process(ParameterHintsPassFactory.java:122)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.lambda$doCollectInformation$2(ParameterHintsPassFactory.java:94)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.doCollectInformation(ParameterHintsPassFactory.java:94)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by gavinking** [comment] 2017-04-14 18:35
Dupe of fixed bug #623, it seems to me.

**Closed by gavinking** 2017-04-14 18:35 UTC

**Comment by sollecitom** [comment] 2017-04-14 18:40
Looks like it, but still happening for me.

**Comment by gavinking** [comment] 2017-04-14 18:42
@sollecitom are you using a build of the plugin from current git?

**Comment by sollecitom** [comment] 2017-04-14 20:49
My bad, just checked and my build was previous the fix. Thanks :)
